version: '3'
name: prod-blog-0.1
services:
  web:
    build:
      context: ..
      dockerfile: ./Docker/prod.Dockerfile
    image: prod/web:0.31
    environment:
      - NODE_ENV=production
    env_file:
      - ../.envs/.prod.env
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ../:/app  
      - /app/node_modules
      - /app/.next