version: '3'
name: staging-blog-0.1
services:
  web:
    build:
      context: ..
      dockerfile: ./Docker/prod.Dockerfile
    image: prod/web:0.11
    environment:
      - NODE_ENV=production
    env_file:
      - ../.envs/.prod.env
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ../:/app  
      - /app/node_modules
      - /app/.next 

  nginx:
    image: nginx:1.29.1-bookworm-perl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    user: root
    restart: unless-stopped

  certbot:
    image: certbot/certbot:v5.0.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

volumes:
  data_blog:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/01_SoraKobra/tailwind-sorakobra-blog
