version: '3'
name: staging-blog-0.1
services:
  web:
    build:
      context: ..
      dockerfile: ./Docker/staging.Dockerfile
    image: staging/web:1.4
    environment:
      - WATCHPACK_POLLING=true  # Enable polling for file changes
      - NODE_ENV=development
    env_file:
      - ../.envs/.staging.env 
    command: npm run dev 
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ../:/app  
      - /app/node_modules 
      - /app/.next  
volumes:
  data_blog:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/redaer/Documents/WORK/00_YACODATA/02_ALBAB/tailwind-nextjs-starter-blog
