version: '3'
name: prod-blog-0.1
services:
  web:
    build:
      context: ..
      dockerfile: ./Docker/staging.Dockerfile
    image: staging/web:0.31
    user: root
    environment:
      - WATCHPACK_POLLING=true  # Enable polling for file changes
      - NODE_ENV=development  # Set environment variables
    env_file:
      - ../.envs/.staging.env  # Load environment variables from a file
    command: npm run dev 
    ports:
      - "3000:3000"
    volumes:
      - ../:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Prevent overwriting node_modules in the container
      - /app/.next  # Prevent overwriting .next build artifacts
volumes:
  data_blog:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PATH
