name: Build and Push Image

on:
  push:
    branches: [ staging ]
  workflow_dispatch:  # Allows manual triggering

env:
  IMAGE_NAME: albab/prod/sorakobra-web

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install CA Certificate
      if: ${{ secrets.REGISTRY_CA_CERT }}
      run: |
        # Create certs directory in workspace
        mkdir -p $HOME/.docker/certs.d/$(echo ${{ secrets.REGISTRY }} | cut -d/ -f1)
        
        # Save certificate with proper permissions
        echo "${{ secrets.REGISTRY_CA_CERT }}" | base64 -d > $HOME/.docker/certs.d/$(echo ${{ secrets.REGISTRY }} | cut -d/ -f1)/ca.crt
        
        # Configure Docker to use custom certs path
        echo "{\"tlscacert\": \"$HOME/.docker/certs.d/$(echo ${{ secrets.REGISTRY }} | cut -d/ -f1)/ca.crt\"}" > $HOME/.docker/config.json

    - name: Restart Docker
      run: sudo systemctl restart docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host

    - name: Login to Hetzner Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Docker/prod.Dockerfile
        tags: |
          ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        cache: true