name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag to deploy (default: latest)'
        required: false
        default: latest

env:
  REGISTRY: registry-albab-prod
  IMAGE_NAME: albab/staging/sorakobra-web
  K8S_NAMESPACE: prod
  DEPLOYMENT_NAME: sorakobra-frontend

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Kubernetes tools
      uses: azure/setup-helm@v3

    - name: Configure Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG" > ~/.kube/config
        kubectl config use-context your-cluster-context

    - name: Update Deployment
      run: |
        TAG=${{ github.event.inputs.image-tag || 'latest' }}
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          react-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG \
          -n ${{ env.K8S_NAMESPACE }}